### ISSUE TITLE
Modifying the model structure

### ISSUE THREAD

**Issue by 1197155807** [xinwucwp/faultSeg#12]
Dear Dr. Wu
thank you for your great effort。
If I want to modify the model model/fseg-60.hdf5 file and I want to use a new structure as my convolutional neural network, how should I modify it?
Thanks again.

**Comment by llmpass** [comment]
You can simply write/design a new one from scratch, I see it's better and way simpler than modifying from the existing hdf5 file.

**Comment by 1197155807** [comment]
First of all, thank you very much for your answer. If I want to build my own HDF5 model, is there any way that I could see the specific code in the file FSEG-60. HDF5? I want to know, I want to know, what package is it built from.
Thank you again!

**Comment by llmpass** [comment]
It's created in train.py: https://github.com/xinwucwp/faultSeg/blob/40a3bae2b7980916b7f3091ca058e363b05696fc/train.py#L44
You can go modify unet3.py to create a new model and change the file name in train.py accordingly. The package is keras. Hope this helps.
