### ISSUE TITLE
Whether  Inline, Crossline and Time is even？

### ISSUE THREAD

**Issue by 1197155807** [xinwucwp/faultSeg#13]
Dear Dr. Wu
I would like to ask if there are any requirements for Inline, Crossline and Time in predicting faults on my own data set.
Whether it must be an even number or 2 to the power of n？

Is there a limit to the size of the predicted data？

Thanks again.

**Comment by humbertogeologia** [comment]
Hi, fantastic piece of work. The result "fp.dat" can be converted to sgy? If yes can you please tell me how to do it with python? My aim is to import the results to petrel or opendtect

**Comment by augustoicaro** [comment]
@humbertogeologia, please see the snippet in https://github.com/xinwucwp/faultSeg/issues/2#issuecomment-550130689.

Best,

**Comment by llmpass** [comment]
> Dear Dr. Wu I would like to ask if there are any requirements for Inline, Crossline and Time in predicting faults on my own data set. Whether it must be an even number or 2 to the power of n？
> 
> Is there a limit to the size of the predicted data？
> 
> Thanks again.

To feed the data into the current Unet structure, the size of the cube must be divisible of 8. However, you can always cut your data into such pieces before feeding them into the network.
