### ISSUE TITLE
Range of peak frequency in training data

### ISSUE THREAD

**Issue by maguman** [xinwucwp/faultSeg#15]
Excellent work here!

I would like to know the predefined range of peak frequency used for generating this training data.  
Also, your reason for determining those peak frequencies.
Thank you in advance.

Yonghyun

**Comment by maguman** [comment]
I got to know that this issue is trivial. Selected frequencies may depend on their target data. It would be okay to close this issue.

**Comment by llmpass** [comment]
> I got to know that this issue is trivial. Selected frequencies may depend on their target data. It would be okay to close this issue.

exactly true.
