### ISSUE TITLE
train the model

### ISSUE THREAD

**Issue by super-wu12138** [xinwucwp/faultSeg#16]
Hi, Dr Wu. 
   Thank you very much for this awesome research！
   I have run the code successfully, but it seems that I can't get "pretrained_model.hdf5" by training the model.  Could you please tell me How to train the model will get "pretrained_model.hdf5".
Thanks

**Comment by llmpass** [comment]
hi, the google drive link share in this repo still alive:
https://drive.google.com/drive/folders/1q8sAoLJgbhYHRubzyqMi9KkTeZWXWtNd
I had just double checked it.

**Comment by super-wu12138** [comment]
Okay, thanks for your comments. I have download "pretrained_model.hdf5" before successfully, but my doubt is how can I get  the "pretrained_model.hdf5" by running code or train the model “Unet3” ，not download via the he google drive link.

**Comment by llmpass** [comment]
I think just following the setting in the paper will more or less achieve a very similar (off course not 100% the same) model.
