### ISSUE TITLE
Prediction in new dataset with different dimensions

### ISSUE THREAD

**Issue by kasyful** [xinwucwp/faultSeg#19]
Dear Dr @xinwucwp and Dr @llmpass ,

Thank you for the excellent publication.

How can I apply the data to a new dataset? I have no issue when applying it to the datasets that have the same dimensions (512,384,128) , how could i apply to a new dataset with different dimensions ie (800, 1600, 512) which could be divide by 8.

thank you

**Comment by llmpass** [comment]
This model is fully-connected CNN, have you tried to just apply the pretrained model directly on your data?
